name: openvpr
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - faiss-cpu=1.8.0
  - pip
  - pip:
      - torch==2.3.1
      - torchvision==0.18.1
      - PyYAML==6.0.1
      - lightning==2.3.3
      - pandas==2.2.2
      - kaggle==1.6.14
      - rich==13.7.1
      - pytorch-metric-learning==2.5.0
      - timm==1.0.7
      - tensorboard==2.17
